- name: docker build and push
  hosts: docker  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      
    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/jpetstore

    - name: tag image
      command: docker tag petstore:latest iqbal777/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "user id"
        password: "user pw"

    - name: Push image
      command: docker push iqbal777/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 iqbal777/petstore:latest
